language: java
jdk:
  - oraclejdk8

install: ant
script: ant test

notifications:
 email:
  recipients:
   - fbertolotto@fi.uba.ar
   - msantoni@fi.uba.ar
   - nramirez@fi.uba.ar
   - andyfer91@gmail.com
  on_success: always
  on_failure: always