env:
 global:
  - CODECOV_TOKEN=:95a8244b-4f8f-4baf-93fd-a35994a44def

language: java
jdk:
  - oraclejdk8

install: ant
script: ant test

after_success:
 - bash <(curl -s https://codecov.io/bash) -t token

notifications:
 email:
  recipients:
   - fbertolotto@fi.uba.ar
   - msantoni@fi.uba.ar
   - nramirez@fi.uba.ar
   - andyfer91@gmail.com
  on_success: always
  on_failure: always